name: daily-microcap

on:
  schedule:
    - cron: "5 15 * * *"  # 18:05 EEST = 15:05 UTC
  workflow_dispatch:

concurrency:
  group: daily-microcap
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check trading day (XNYS)
        id: marketday
        run: |
          python - <<'PY'
          import sys, datetime as dt, os
          try:
              import pandas_market_calendars as mcal
              nyse = mcal.get_calendar('XNYS')
              today = dt.date.today()
              sched = nyse.schedule(start_date=today, end_date=today)
              is_open = 'true' if not sched.empty else 'false'
          except Exception:
              # fallback: skip ainult nädalavahetusel
              is_open = 'false' if dt.date.today().weekday() >= 5 else 'true'
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"is_open={is_open}\n")
          PY

      - name: Install deps
        if: steps.marketday.outputs.is_open == 'true'
        run: |
          python -m venv .venv
          .
